//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using HRMS.holders;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class HUMAN_MANAGEMENTEntities : DbContext
    {
        public HUMAN_MANAGEMENTEntities()
            : base(DBManagement.getConnection(AuthHolder.Username, AuthHolder.Password))
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Timekeeping> Timekeepings { get; set; }
    }
}
