//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int id { get; set; }
        public int employeeId { get; set; }
        public int amount { get; set; }
        public string month { get; set; }
        public System.DateTime createdTime { get; set; }
        public System.DateTime updatedTime { get; set; }
        public int workdays { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
